const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/nike/shirts/p1.jpg', 
      price: 88,
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/adidas/shirts/p2.jpg',
      price: 75,
      countInStock: 25,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/nike/pants/p3.jpg',
      price: 85,
      countInStock: 20,
      brand: 'Nike',
      rating: 4.6,
      numReviews: 18,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/adidas/pants/p4.jpg',
      price: 110,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};

export default data